# Generated by Django 4.1.7 on 2023-04-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_musicdatabases_delete_musicdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='musicDatabased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('album', models.ImageField(upload_to='myapp')),
                ('artist', models.CharField(max_length=255)),
                ('song', models.FileField(upload_to='myapp')),
                ('track', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.DeleteModel(
            name='musicDatabases',
        ),
    ]
